spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AppForChuYan?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true #自动提交从池中返回的连接,默认true
      max-lifetime: 1800000 #池中连接的最长生命周期,默认1800000(30m)
      connection-timeout: 30000 #客户端等待池中连接的最大毫秒数,如果在没有连接可用的情况下超过此时间,则将抛出SQLException,默认30000(30s)
      maximum-pool-size: 10 #允许池到达的最大大小,包括空闲和正在使用的连接,对此的合理值最好由执行环境决定,默认10
      #minimum-idle 尝试在池中维护的最小空闲连接数,不用设置,默认值与maximum-pool-size相同
      idle-timeout: 600000 #允许连接在池中处于空闲状态的最长时间,默认600000(10m)
  jpa:
    open-in-view: false
    generate-ddl: true
  mail:
    username: 1223344454@qq.com
    password: udxhjryfjimjheha
    host: smtp.qq.com
    #    设置是否需要认证
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          host: smtp.qq.com
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          port: 465